"""
VLM Fine-tuning System for Tool Selection
========================================

Implements supervised fine-tuning and reinforcement learning for VLM tool selection.
Uses the training data generated by VLMToolTrainingSystem to train models.
"""

import asyncio
import json
import os
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer, AutoModelForCausalLM, 
    TrainingArguments, Trainer, 
    DataCollatorForLanguageModeling
)
import numpy as np
from typing import Dict, Any, List, Tuple, Optional
from pathlib import Path
import logging
from dataclasses import dataclass
import pickle
from datetime import datetime

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

@dataclass
class FineTuningConfig:
    """Configuration for VLM fine-tuning"""
    model_name: str = "microsoft/DialoGPT-medium"  # Base model
    max_length: int = 1024
    batch_size: int = 4
    learning_rate: float = 5e-5
    num_epochs: int = 3
    warmup_steps: int = 100
    save_steps: int = 500
    eval_steps: int = 100
    output_dir: str = "vlm_tool_model"
    gradient_accumulation_steps: int = 2
    fp16: bool = True if torch.cuda.is_available() else False

class VLMToolDataset(Dataset):
    """Dataset for VLM tool selection training"""
    
    def __init__(self, training_examples: List[Dict], tokenizer, max_length: int = 1024):
        self.examples = training_examples
        self.tokenizer = tokenizer
        self.max_length = max_length
        
        # Prepare data
        self.processed_examples = self._process_examples()
    
    def _process_examples(self) -> List[Dict[str, Any]]:
        """Process training examples into tokenizable format"""
        processed = []
        
        for example in self.examples:
            # Reconstruct context and target
            context = example["context_state"]
            target_tool = example["correct_tool_invocation"]
            
            # Build input prompt
            prompt = self._build_training_prompt(context)
            
            # Build target response
            target_response = self._build_target_response(target_tool)
            
            # Combine for training
            full_text = f"{prompt}\n\nRESPONSE:\n{target_response}"
            
            processed.append({
                "input_text": prompt,
                "target_text": target_response,
                "full_text": full_text,
                "reward_score": example["reward_score"]
            })
        
        return processed
    
    def _build_training_prompt(self, context: Dict[str, Any]) -> str:
        """Build training prompt from context"""
        
        prompt_parts = [
            "AVAILABLE MICROSERVICE TOOLS:",
            "",
            "PERCEPTION TOOLS:",
            "  - camera_service.capture_first_person_view(actor_name: str): Capture first-person view screenshot",
            "  - image_analysis_service.analyze_room_from_image(image_path: str): Analyze image for room type",
            "  - image_analysis_service.identify_furniture_objects(image_path: str): Identify furniture objects",
            "",
            "INFORMATION TOOLS:",
            "  - spatial_service.get_current_position(actor_name: str): Get actor's current position",
            "  - spatial_service.detect_room(actor_name: str): Detect current room",
            "  - camera_service.get_camera_info(actor_name: str): Get camera information",
            "",
            "PLANNING TOOLS:",
            "  - spatial_service.get_navigation_context(actor_name: str): Get navigation options",
            "",
            "ACTION TOOLS:",
            "  - movement_service.move_actor_to_position(target_position: List[float]): Move to position",
            "  - movement_service.move_to_room(target_room: str): Move to specific room",
            "  - movement_service.rotate_actor(rotation_change: List[float]): Rotate actor",
            "",
            "GUIDANCE TOOLS:",
            "  - orchestration_service.vlm_navigation_guidance(task_description: str): Get comprehensive guidance",
            "",
            "=" * 80,
            "",
            "CURRENT CONTEXT:",
            f"Task: {context['task_description']}",
            f"Current Room: {context['current_room']}",
            f"Actor Position: ({context['actor_position'][0]:.1f}, {context['actor_position'][1]:.1f}, {context['actor_position'][2]:.1f})",
            f"Visible Objects: {', '.join(context['visible_objects']) if context['visible_objects'] else '[none detected]'}",
            f"Images Available: {'Yes' if context.get('first_person_image_path') else 'No'}",
            "",
            "INSTRUCTION:",
            "Select the most appropriate tool to call next. Provide your response in this format:",
            "TOOL: service_name.tool_name",
            "PARAMETERS: {parameter_dict}",
            "REASONING: Brief explanation"
        ]
        
        return "\n".join(prompt_parts)
    
    def _build_target_response(self, tool_invocation: Dict[str, Any]) -> str:
        """Build target response from tool invocation"""
        
        tool_id = f"{tool_invocation['service_name']}_service.{tool_invocation['tool_name']}"
        parameters = json.dumps(tool_invocation['parameters'])
        reasoning = tool_invocation['reasoning']
        
        return f"TOOL: {tool_id}\nPARAMETERS: {parameters}\nREASONING: {reasoning}"
    
    def __len__(self):
        return len(self.processed_examples)
    
    def __getitem__(self, idx):
        example = self.processed_examples[idx]
        
        # Tokenize full text for training
        encoding = self.tokenizer(
            example["full_text"],
            truncation=True,
            max_length=self.max_length,
            padding="max_length",
            return_tensors="pt"
        )
        
        return {
            "input_ids": encoding["input_ids"].squeeze(),
            "attention_mask": encoding["attention_mask"].squeeze(),
            "labels": encoding["input_ids"].squeeze(),  # For causal LM
            "reward_score": torch.tensor(example["reward_score"], dtype=torch.float32)
        }

class VLMToolFinetuner:
    """Fine-tuning system for VLM tool selection"""
    
    def __init__(self, config: FineTuningConfig = None):
        self.config = config or FineTuningConfig()
        
        # Initialize model and tokenizer
        self.tokenizer = None
        self.model = None
        self.trainer = None
        
        # Training data
        self.train_dataset = None
        self.eval_dataset = None
        
        self._initialize_model()
    
    def _initialize_model(self):
        """Initialize the base model and tokenizer"""
        
        logger.info(f"Loading model: {self.config.model_name}")
        
        # Load tokenizer
        self.tokenizer = AutoTokenizer.from_pretrained(self.config.model_name)
        
        # Add padding token if not present
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
        
        # Load model
        self.model = AutoModelForCausalLM.from_pretrained(
            self.config.model_name,
            torch_dtype=torch.float16 if self.config.fp16 else torch.float32,
            device_map="auto" if torch.cuda.is_available() else None
        )
        
        # Resize token embeddings if needed
        self.model.resize_token_embeddings(len(self.tokenizer))
        
        logger.info("Model and tokenizer initialized successfully")
    
    def load_training_data(self, training_data_path: str, train_split: float = 0.8):
        """Load and split training data"""
        
        logger.info(f"Loading training data from: {training_data_path}")
        
        with open(training_data_path, 'rb') as f:
            training_data = pickle.load(f)
        
        examples = training_data["examples"]
        
        # Split into train/eval
        split_idx = int(len(examples) * train_split)
        train_examples = examples[:split_idx]
        eval_examples = examples[split_idx:]
        
        # Create datasets
        self.train_dataset = VLMToolDataset(
            train_examples, self.tokenizer, self.config.max_length
        )
        self.eval_dataset = VLMToolDataset(
            eval_examples, self.tokenizer, self.config.max_length
        )
        
        logger.info(f"Training examples: {len(train_examples)}")
        logger.info(f"Evaluation examples: {len(eval_examples)}")
    
    def setup_training(self):
        """Setup training arguments and trainer"""
        
        training_args = TrainingArguments(
            output_dir=self.config.output_dir,
            num_train_epochs=self.config.num_epochs,
            per_device_train_batch_size=self.config.batch_size,
            per_device_eval_batch_size=self.config.batch_size,
            gradient_accumulation_steps=self.config.gradient_accumulation_steps,
            learning_rate=self.config.learning_rate,
            warmup_steps=self.config.warmup_steps,
            logging_steps=50,
            save_steps=self.config.save_steps,
            eval_steps=self.config.eval_steps,
            evaluation_strategy="steps",
            save_strategy="steps",
            load_best_model_at_end=True,
            metric_for_best_model="eval_loss",
            greater_is_better=False,
            fp16=self.config.fp16,
            dataloader_pin_memory=False,
            remove_unused_columns=False
        )
        
        # Data collator
        data_collator = DataCollatorForLanguageModeling(
            tokenizer=self.tokenizer,
            mlm=False  # Causal LM, not masked LM
        )
        
        # Initialize trainer
        self.trainer = Trainer(
            model=self.model,
            args=training_args,
            train_dataset=self.train_dataset,
            eval_dataset=self.eval_dataset,
            data_collator=data_collator,
            tokenizer=self.tokenizer
        )
        
        logger.info("Training setup complete")
    
    def train(self):
        """Execute fine-tuning"""
        
        logger.info("Starting fine-tuning...")
        
        # Train the model
        self.trainer.train()
        
        # Save the final model
        self.trainer.save_model()
        self.tokenizer.save_pretrained(self.config.output_dir)
        
        logger.info(f"Fine-tuning complete. Model saved to: {self.config.output_dir}")
    
    def evaluate_model(self, test_examples: List[Dict[str, Any]] = None) -> Dict[str, float]:
        """Evaluate the fine-tuned model"""
        
        if test_examples is None:
            test_examples = self.eval_dataset.processed_examples[:10]  # Use first 10 eval examples
        
        logger.info(f"Evaluating model on {len(test_examples)} examples")
        
        correct_predictions = 0
        total_predictions = len(test_examples)
        
        self.model.eval()
        
        for i, example in enumerate(test_examples):
            # Get model prediction
            prediction = self.predict_tool(example["input_text"])
            
            # Check if prediction matches target
            target_tool = self._extract_tool_from_text(example["target_text"])
            predicted_tool = self._extract_tool_from_text(prediction)
            
            if predicted_tool == target_tool:
                correct_predictions += 1
            
            logger.info(f"Example {i+1}: {'✓' if predicted_tool == target_tool else '✗'}")
            logger.info(f"  Target: {target_tool}")
            logger.info(f"  Predicted: {predicted_tool}")
        
        accuracy = correct_predictions / total_predictions
        
        results = {
            "accuracy": accuracy,
            "correct_predictions": correct_predictions,
            "total_predictions": total_predictions
        }
        
        logger.info(f"Evaluation Results: {results}")
        return results
    
    def predict_tool(self, input_prompt: str, max_new_tokens: int = 200) -> str:
        """Generate tool prediction for given input"""
        
        # Tokenize input
        inputs = self.tokenizer(
            input_prompt + "\n\nRESPONSE:\n",
            return_tensors="pt",
            truncation=True,
            max_length=self.config.max_length - max_new_tokens
        )
        
        # Generate response
        with torch.no_grad():
            outputs = self.model.generate(
                inputs["input_ids"],
                attention_mask=inputs["attention_mask"],
                max_new_tokens=max_new_tokens,
                do_sample=True,
                temperature=0.7,
                top_p=0.9,
                pad_token_id=self.tokenizer.eos_token_id
            )
        
        # Decode response
        full_response = self.tokenizer.decode(outputs[0], skip_special_tokens=True)
        
        # Extract generated part
        response_start = full_response.find("RESPONSE:\n")
        if response_start != -1:
            generated_response = full_response[response_start + len("RESPONSE:\n"):].strip()
        else:
            generated_response = full_response.split(input_prompt)[-1].strip()
        
        return generated_response
    
    def _extract_tool_from_text(self, text: str) -> str:
        """Extract tool name from response text"""
        
        lines = text.split('\n')
        for line in lines:
            if line.strip().startswith("TOOL:"):
                return line.replace("TOOL:", "").strip()
        
        return "unknown"

class ReinforcementLearningTrainer:
    """Reinforcement learning trainer for VLM tool selection"""
    
    def __init__(self, base_model_path: str):
        self.base_model_path = base_model_path
        self.policy_model = None
        self.value_model = None
        
        # RL hyperparameters
        self.gamma = 0.99  # Discount factor
        self.lambda_gae = 0.95  # GAE lambda
        self.clip_epsilon = 0.2  # PPO clip epsilon
        self.value_loss_coef = 0.5
        self.entropy_coef = 0.01
        
    def initialize_models(self):
        """Initialize policy and value models"""
        
        # Load fine-tuned model as base
        tokenizer = AutoTokenizer.from_pretrained(self.base_model_path)
        base_model = AutoModelForCausalLM.from_pretrained(self.base_model_path)
        
        # Policy model (for action selection)
        self.policy_model = base_model
        
        # Value model (for state value estimation)
        # In practice, you might want a separate model or additional head
        self.value_model = base_model  # Simplified for this example
        
        logger.info("RL models initialized")
    
    def collect_trajectories(self, num_episodes: int = 100) -> List[Dict[str, Any]]:
        """Collect trajectories using current policy"""
        
        trajectories = []
        
        for episode in range(num_episodes):
            # This would interact with VESPER environment
            # For now, return simulated trajectories
            trajectory = {
                "states": [],
                "actions": [],
                "rewards": [],
                "values": [],
                "log_probs": []
            }
            trajectories.append(trajectory)
        
        return trajectories
    
    def compute_advantages(self, trajectories: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Compute GAE advantages"""
        
        for trajectory in trajectories:
            rewards = trajectory["rewards"]
            values = trajectory["values"]
            
            # Compute advantages using GAE
            advantages = []
            gae = 0
            
            for t in reversed(range(len(rewards))):
                if t == len(rewards) - 1:
                    next_value = 0
                else:
                    next_value = values[t + 1]
                
                delta = rewards[t] + self.gamma * next_value - values[t]
                gae = delta + self.gamma * self.lambda_gae * gae
                advantages.insert(0, gae)
            
            trajectory["advantages"] = advantages
        
        return trajectories
    
    def update_policy(self, trajectories: List[Dict[str, Any]]):
        """Update policy using PPO"""
        
        # This would implement PPO update logic
        # Simplified placeholder for this example
        
        total_policy_loss = 0
        total_value_loss = 0
        
        for trajectory in trajectories:
            # Compute policy loss, value loss, etc.
            # Update models
            pass
        
        logger.info(f"Policy updated. Policy loss: {total_policy_loss}, Value loss: {total_value_loss}")

# Example usage and testing
async def main():
    """Main function for testing fine-tuning system"""
    
    print("🚀 Starting VLM Tool Selection Fine-tuning")
    
    # Configuration
    config = FineTuningConfig(
        model_name="microsoft/DialoGPT-small",  # Smaller model for testing
        num_epochs=2,
        batch_size=2,
        max_length=512
    )
    
    # Initialize fine-tuner
    finetuner = VLMToolFinetuner(config)
    
    # Check if training data exists
    training_data_files = list(Path("vlm_training_data").glob("vlm_tool_training_data_*.pkl"))
    
    if not training_data_files:
        print("❌ No training data found. Please run vlm_tool_selection_training.py first.")
        return
    
    # Use most recent training data
    latest_data_file = max(training_data_files, key=os.path.getctime)
    print(f"📁 Using training data: {latest_data_file}")
    
    # Load training data
    finetuner.load_training_data(str(latest_data_file))
    
    # Setup training
    finetuner.setup_training()
    
    # Start fine-tuning
    print("🔥 Starting fine-tuning process...")
    finetuner.train()
    
    # Evaluate model
    print("📊 Evaluating fine-tuned model...")
    results = finetuner.evaluate_model()
    
    print(f"✅ Fine-tuning complete!")
    print(f"📈 Model accuracy: {results['accuracy']:.2%}")
    print(f"💾 Model saved to: {config.output_dir}")
    
    # Test prediction
    print("\n🧪 Testing prediction on example:")
    
    test_prompt = """AVAILABLE MICROSERVICE TOOLS:

PERCEPTION TOOLS:
  - camera_service.capture_first_person_view(actor_name: str): Capture first-person view screenshot

INFORMATION TOOLS:
  - spatial_service.get_current_position(actor_name: str): Get actor's current position

ACTION TOOLS:
  - movement_service.move_to_room(target_room: str): Move to specific room

================================================================================

CURRENT CONTEXT:
Task: Navigate to the kitchen
Current Room: unknown
Actor Position: (0.0, 0.0, 0.0)
Visible Objects: [none detected]
Images Available: No

INSTRUCTION:
Select the most appropriate tool to call next. Provide your response in this format:
TOOL: service_name.tool_name
PARAMETERS: {parameter_dict}
REASONING: Brief explanation"""
    
    prediction = finetuner.predict_tool(test_prompt)
    print("Prediction:")
    print(prediction)

if __name__ == "__main__":
    asyncio.run(main())
