import bge
import mathutils
import os
import sys
import json
import time

def setup_python_path():
    """Setup path to access LLM client"""
    try:
        vesper_root = r"C:\Users\hbui11\Desktop\vesper_llm"

        if vesper_root not in sys.path:
            sys.path.insert(0, vesper_root)
            print(f"✅ BGE: Path setup complete")

        # Load environment variables
        env_path = os.path.join(vesper_root, "backend", "app", "llm", ".env")
        if os.path.exists(env_path):
            try:
                from dotenv import load_dotenv
                load_dotenv(env_path)
                print(f"✅ BGE: Environment loaded")
            except ImportError:
                with open(env_path, 'r') as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith('#') and '=' in line:
                            key, value = line.split('=', 1)
                            os.environ[key.strip()] = value.strip()

        return True
    except Exception as e:
        print(f"❌ BGE: Path setup failed: {e}")
    return False

path_ok = setup_python_path()

# =============================
# LLM client import
# =============================
LLM_AVAILABLE = False
few_shot_system = None

if path_ok:
    try:
        from backend.app.llm.client import chat_completion, chat_completion_with_vision
        from backend.app.llm.few_shot_navigation import VESPERFewShotPrompts, validate_json_response
        LLM_AVAILABLE = True
        print("🔗 LLM: Connected")
        
        # Initialize few-shot system - define captures_dir inline to avoid ordering issues
        vesper_root = r"C:\Users\hbui11\Desktop\vesper_llm"
        captures_dir = os.path.join(vesper_root, "blender", "captures")
        os.makedirs(captures_dir, exist_ok=True)
        
        few_shot_system = VESPERFewShotPrompts(captures_dir)
        print("🎯 Few-shot navigation system initialized")
        
    except ImportError as e:
        print(f"❌ BGE: LLM not available - {e}")
        few_shot_system = None
    except Exception as e:
        print(f"❌ BGE: Few-shot system initialization failed - {e}")
        few_shot_system = None
        # Continue without few-shot system
else:
    print("❌ BGE: Setup failed")
    few_shot_system = None

# =============================
# Task loading helpers
# =============================
def load_vesper_tasks():
    """Load tasks from vesper_tasks.txt generated by the addon"""
    try:
        # Check multiple possible locations
        task_files = [
            r"C:\Users\hbui11\AppData\Roaming\UPBGE\Blender\4.4\scripts\addons\vesper_tools\..\..\vesper_tasks.txt",
            r"C:\Users\hbui11\AppData\Roaming\UPBGE\Blender\4.4\scripts\vesper_tasks.txt",
            os.path.join(os.path.dirname(__file__), "vesper_tasks.txt"),
            os.path.join(r"C:\Users\hbui11\Desktop\vesper_llm\blender", "vesper_tasks.txt")
        ]
        
        for task_file in task_files:
            if os.path.exists(task_file):
                print(f"📝 BGE: Loading tasks from {task_file}")
                with open(task_file, 'r', encoding='utf-8') as f:
                    content = f.read().strip()
                    if content:
                        # Parse tasks - try both comma and pipe separation
                        if '|' in content:
                            tasks = [task.strip() for task in content.split('|') if task.strip()]
                        else:
                            tasks = [task.strip() for task in content.split(',') if task.strip()]
                        print(f"✅ BGE: Loaded {len(tasks)} tasks: {tasks}")
                        return tasks
        
        print("⚠️ BGE: No vesper_tasks.txt found, using defaults")
        return None
        
    except Exception as e:
        print(f"❌ BGE: Error loading tasks: {e}")
        return None

# =============================
# Screenshot helpers (non-blocking)
# =============================
def _init_shot_state():
    """Ensure global shot state exists."""
    if not hasattr(bge.logic, "_vesper_shot"):
        bge.logic._vesper_shot = {
            "pending": False,
            "path": None,
            "start_time": 0.0,
            "tries": 0,
        }

def _captures_dir():
    vesper_root = r"C:\Users\hbui11\Desktop\vesper_llm"
    captures_dir = os.path.join(vesper_root, "blender", "captures")
    os.makedirs(captures_dir, exist_ok=True)
    return captures_dir

def _next_screenshot_path(captures_dir):
    existing_files = [f for f in os.listdir(captures_dir) if f.startswith("bge_") and f.endswith(".png")]
    if existing_files:
        nums = []
        for f in existing_files:
            try:
                nums.append(int(f.split("_")[1].split(".")[0]))
            except Exception:
                pass
        n = (max(nums) + 1) if nums else 1
    else:
        n = 1
    p = os.path.join(captures_dir, f"bge_{n:03d}.png")
    while os.path.exists(p):
        n += 1
        p = os.path.join(captures_dir, f"bge_{n:03d}.png")
    return p

def request_bird_eye_screenshot():
    """
    Kick off a screenshot of the next rendered frame from BirdEyeCamera.
    Non-blocking: returns immediately; result is polled via poll_screenshot_ready().
    """
    import bge.render

    _init_shot_state()
    scene = bge.logic.getCurrentScene()

    # Find BirdEyeCamera
    camera = scene.objects.get("BirdEyeCamera")
    if not camera:
        # Fallback: try to find any camera-like object
        print("⚠️ BGE: No BirdEyeCamera found. Searching for camera-like object...")
        for obj in scene.objects:
            if 'camera' in obj.name.lower() or 'cam' in obj.name.lower():
                camera = obj
                break
        if not camera:
            print("❌ BGE: No camera available")
            return None

    # ENHANCED: Optimize camera settings for better screenshot quality
    try:
        scene.active_camera = camera
        
        # Ensure camera has optimal settings for screenshots
        if hasattr(camera, 'lens'):
            # Adjust camera properties for better coverage and clarity
            original_lens = camera.lens
            # Use a wider lens for better room coverage in bird's eye view
            if camera.lens < 35:
                camera.lens = 35  # Wider view for better room visibility
                print(f"📷 BGE: Adjusted camera lens from {original_lens} to {camera.lens}")
        
        # Optimize camera position if needed (bird's eye view should be high up)
        cam_pos = camera.worldPosition
        if cam_pos.z < 5.0:  # Camera should be high up for bird's eye view
            print(f"⚠️ BGE: Camera height may be too low: {cam_pos.z}")
            print("💡 BGE: Consider positioning BirdEyeCamera higher (Z > 8) for better overview")
            
    except Exception as e:
        print(f"⚠️ BGE: Camera optimization error: {e}")

    # Ensure we capture from the right camera
    try:
        scene.active_camera = camera
    except Exception as e:
        print(f"⚠️ BGE: Camera error: {e}")

    capdir = _captures_dir()
    shot_path = _next_screenshot_path(capdir)

    # ENHANCED: Take high-quality screenshot for better VLM analysis
    try:        
        print(f"📸 BGE: Capturing high-quality screenshot...")
        
        # Standard BGE screenshot method (no world attribute access)
        bge.render.makeScreenshot(shot_path)
        
        # Additional quality enhancement: Check viewport info if available
        try:
            import bgl
            # Get viewport dimensions for reference
            viewport = bgl.glGetIntegerv(bgl.GL_VIEWPORT)
            print(f"📐 BGE: Current viewport: {viewport[2]}x{viewport[3]}")
        except Exception:
            pass  # Not all BGE versions have bgl access
            
    except Exception as e:
        print(f"❌ BGE: Screenshot capture failed: {e}")
        return None

    st = bge.logic._vesper_shot
    st["pending"] = True
    st["path"] = shot_path
    st["start_time"] = time.time()
    st["tries"] += 1

    return shot_path

def poll_screenshot_ready(min_bytes: int = 2500, timeout_s: float = 5.0):  # Increased min_bytes for higher quality
    _init_shot_state()
    st = bge.logic._vesper_shot
    if not st["pending"]:
        return None

    p = st["path"]
    if p and os.path.exists(p):
        try:
            size = os.path.getsize(p)
            if size >= min_bytes:
                st["pending"] = False
                filename = os.path.basename(p)
                print(f"📸 Screenshot ready: {filename} ({size} bytes)")
                return p
            else:
                print(f"⏳ BGE: Screenshot still rendering... ({size}/{min_bytes} bytes)")
        except Exception as e:
            print(f"⚠️ BGE: Screenshot error: {e}")

    # timeout -> caller may re-request
    if time.time() - st["start_time"] > timeout_s:
        st["pending"] = False
        return "TIMEOUT"

    return None

# =============================
# JSON parsing helpers
# =============================
def extract_and_fix_json(response):
    """Extract and attempt to fix JSON from LLM response"""
    import re
    
    # First, try standard extraction
    json_match = re.search(r'```json\s*(\{.*?\})\s*```', response, re.DOTALL)
    if json_match:
        json_str = json_match.group(1)
        print(f"📦 BGE: Extracted from markdown: {len(json_str)} chars")
    else:
        # Fallback: look for JSON object boundaries
        start = response.find('{')
        end = response.rfind('}') + 1
        if start >= 0 and end > start:
            json_str = response[start:end]
            print(f"📦 BGE: Extracted from boundaries: {len(json_str)} chars")
        else:
            return None
    
    if not json_str:
        return None
    
    # Clean up control characters first
    json_str = re.sub(r'[\x00-\x1f\x7f]', '', json_str)
    
    # Try to parse as-is first
    try:
        import json
        json.loads(json_str)
        print(f"🧹 BGE: JSON is valid as-is: {json_str[:100]}...")
        return json_str
    except json.JSONDecodeError as e:
        print(f"🔧 BGE: JSON needs repair - {e}")
        pass
    
    # Apply targeted fixes for common LLM errors
    try:
        original_json = json_str
        
        # Fix 1: The main issue - missing closing quote before comma
        # Pattern: "Based on furniture around pink dot: [LIVING_ROOM],
        # Should be: "Based on furniture around pink dot: [LIVING_ROOM]",
        json_str = re.sub(r':\s*"([^"]*\[[A-Z_]+\]),', r': "\1",', json_str)
        
        # Fix 2: Handle other missing closing quotes before comma
        # Pattern: "text,   -> "text",
        json_str = re.sub(r':\s*"([^"]*),(\s*"[^"]*"\s*:)', r': "\1",\2', json_str)
        
        # Fix 3: Room names in brackets without quotes
        json_str = re.sub(r'\[([A-Z_]+)\]', r'"\1"', json_str)
        
        if json_str != original_json:
            print(f"🔧 BGE: Applied JSON repairs")
        
        print(f"🧹 BGE: Repaired JSON preview: {json_str[:150]}...")
        return json_str
        
    except Exception as e:
        print(f"❌ BGE: JSON repair failed: {e}")
        return json_str  # Return original if repair fails

def parse_vlm_response(response, current_task=None):
    """Parse VLM response with robust JSON handling and task validation"""
    import json
    
    print(f"📏 BGE: Full response length: {len(response)} characters")
    
    json_str = extract_and_fix_json(response)
    
    if json_str:
        try:
            result = json.loads(json_str)
            print(f"✅ BGE: JSON parsed successfully")
            
            # Check if task is complete based on room analysis
            task_complete = result.get("task_complete", False)
            current_room = result.get("current_room", "UNKNOWN")
            furniture_visible = result.get("furniture_visible", "None specified")
            
            # SERVER-SIDE TASK VALIDATION: Double-check VLM's task completion decision
            if task_complete and current_task:
                task_validated = False
                task_lower = current_task.lower()
                
                # Comprehensive room validation for all supported room types
                if ("kitchen" in task_lower or "cook" in task_lower) and current_room == "KITCHEN":
                    task_validated = True
                elif ("living room" in task_lower or "living" in task_lower or "relax" in task_lower) and current_room == "LIVING_ROOM":
                    task_validated = True
                elif ("bathroom" in task_lower or "prepare" in task_lower or "wash" in task_lower) and current_room == "BATHROOM":
                    task_validated = True
                elif ("bedroom" in task_lower or "sleep" in task_lower or "rest" in task_lower) and current_room == "BEDROOM":
                    task_validated = True
                elif ("office" in task_lower or "work" in task_lower or "study" in task_lower) and current_room == "OFFICE":
                    task_validated = True
                elif ("garage" in task_lower or "car" in task_lower or "park" in task_lower) and current_room == "GARAGE":
                    task_validated = True
                # Also allow generic room name matching
                elif "kitchen" in task_lower and current_room == "KITCHEN":
                    task_validated = True
                elif "living" in task_lower and current_room == "LIVING_ROOM":
                    task_validated = True
                elif "bathroom" in task_lower and current_room == "BATHROOM":
                    task_validated = True
                elif "bedroom" in task_lower and current_room == "BEDROOM":
                    task_validated = True
                elif "office" in task_lower and current_room == "OFFICE":
                    task_validated = True
                elif "garage" in task_lower and current_room == "GARAGE":
                    task_validated = True
                
                if not task_validated:
                    print(f"🚨 BGE: SERVER VALIDATION FAILED!")
                    print(f"   Task: '{current_task}' vs Room: '{current_room}'")
                    print(f"   VLM incorrectly marked task complete - overriding to FALSE")
                    task_complete = False
                    # Force movement to find correct room
                    if "movement_sequence" in result:
                        result["movement_sequence"] = ["UP"]  # Try moving to find correct room
                else:
                    print(f"✅ BGE: SERVER VALIDATION PASSED - Task '{current_task}' matches room '{current_room}'")
            
            print(f"🏠 BGE: Current room identified: {current_room}")
            print(f"🪑 BGE: Furniture visible: {furniture_visible}")
            print(f"✅ BGE: Task complete: {task_complete}")

            if "movement_sequence" in result and isinstance(result["movement_sequence"], list):
                # Extract movement directions from potentially descriptive text
                raw_sequence = result["movement_sequence"]
                sequence = []
                
                for move in raw_sequence:
                    # Handle both plain directions and descriptive formats
                    if isinstance(move, str):
                        move_upper = move.upper()
                        # Extract all direction keywords from the text
                        directions_found = []
                        if "UP" in move_upper:
                            directions_found.append("UP")
                        if "DOWN" in move_upper:
                            directions_found.append("DOWN")
                        if "LEFT" in move_upper:
                            directions_found.append("LEFT")
                        if "RIGHT" in move_upper:
                            directions_found.append("RIGHT")
                        if "STAY" in move_upper:
                            directions_found.append("STAY")
                        
                        # If we found directions, add them; otherwise add the raw move
                        if directions_found:
                            sequence.extend(directions_found)
                        else:
                            # Maybe it's already a clean direction
                            clean_move = move.strip().upper()
                            if clean_move in ["UP", "DOWN", "LEFT", "RIGHT", "STAY"]:
                                sequence.append(clean_move)
                            else:
                                print(f"⚠️ BGE: Unrecognized move format: '{move}', defaulting to STAY")
                                sequence.append("STAY")
                    else:
                        print(f"⚠️ BGE: Non-string move: {move}, defaulting to STAY")
                        sequence.append("STAY")
                
                print(f"🔄 BGE: Raw sequence: {raw_sequence}")
                print(f"🎯 BGE: Extracted sequence: {sequence}")
                
                if sequence:
                    return {
                        "movement_sequence": sequence, 
                        "reasoning": result.get('reasoning', ''),
                        "task_complete": task_complete,
                        "current_room": current_room,
                        "furniture_visible": furniture_visible
                    }
                else:
                    print(f"❌ BGE: No valid movements extracted from: {raw_sequence}")
                    
                    # Check for oscillation patterns (template responses)
                    furniture_str = str(furniture_visible).lower()
                    reasoning_str = str(result.get('reasoning', '')).lower()
                    
                    if ("list specific furniture" in furniture_str or 
                        "list furniture near pink dot" in reasoning_str or
                        current_room == "UNKNOWN" and len(raw_sequence) > 2):
                        print("🔄 BGE: Detected template/oscillation response - forcing STAY")
                        return {
                            "movement_sequence": ["STAY"], 
                            "reasoning": "Template response detected - staying put to avoid oscillation",
                            "task_complete": False,
                            "current_room": "UNKNOWN",
                            "furniture_visible": ["unclear_image"]
                        }
                    
                    # If no valid movements but task is complete, return STAY
                    if task_complete:
                        return {
                            "movement_sequence": ["STAY"], 
                            "reasoning": result.get('reasoning', ''),
                            "task_complete": task_complete,
                            "current_room": current_room,
                            "furniture_visible": furniture_visible
                        }
            else:
                print(f"❌ BGE: Missing or invalid movement_sequence in result: {list(result.keys())}")
                
        except json.JSONDecodeError as e:
            print(f"⚠️ BGE: JSON parsing error: {e}")
            print(f"📝 BGE: Problematic JSON: {json_str}")
    else:
        print("❌ BGE: No JSON string extracted from response")

    # Show full response for debugging
    print(f"🔍 BGE: FULL VLM RESPONSE DEBUG:")
    print(f"'{response}'")
    
    raise Exception(f"❌ Vision analysis failed - see debug output above")

# =============================
# Enhanced LLM logic with reference image support
# =============================
# =============================
# Enhanced LLM logic with IMAGES-ONLY support (no text fallback)
# =============================

def vision_only_completion(prompt, image_path):
    """Vision completion that NEVER falls back to text-only"""
    import os
    import base64
    
    if not os.path.exists(image_path):
        raise Exception(f"❌ Image file not found: {image_path}")
    
    try:
        # Import required variables
        from backend.app.llm.client import client, HOST, MODEL
        
        print(f"🔍 DEBUG: IMAGES-ONLY completion with HOST='{HOST}', MODEL='{MODEL}'")
        
        # Prepare image for Ollama
        with open(image_path, "rb") as img_file:
            image_data = base64.b64encode(img_file.read()).decode('utf-8')
        
        print(f"🔍 DEBUG: Sending IMAGES-ONLY request...")
        response = client.chat(
            model=MODEL,
            messages=[
                {
                    'role': 'user',
                    'content': prompt,
                    'images': [image_data]
                }
            ],
            options={'temperature': 0.3}
        )
        
        result = response['message']['content'].strip()
        print(f"🔍 DEBUG: IMAGES-ONLY completion successful, response length: {len(result)}")
        
        if not result or len(result) < 20:
            raise Exception("❌ VLM returned insufficient response")
            
        return result
        
    except Exception as e:
        print(f"❌ IMAGES-ONLY completion failed: {e}")
        print(f"🔍 DEBUG: Exception type: {type(e).__name__}")
        raise Exception(f"❌ Vision analysis failed - no text fallback allowed: {e}")

def get_navigation_sequence_with_vlm(screenshot_path, current_task):
    """Get movement sequence from VLM using runtime screenshot + detailed reference image"""
    # Import required modules at function start
    import bge
    import os
    from backend.app.llm.client import chat_completion, HOST, MODEL
    import base64
    
    if not LLM_AVAILABLE:
        raise Exception("❌ LLM not available - cannot proceed without vision capabilities")

    if not screenshot_path or not os.path.exists(screenshot_path):
        raise Exception(f"❌ No valid screenshot available at: {screenshot_path}")

    # Check for detailed reference image
    vesper_root = r"C:\Users\hbui11\Desktop\vesper_llm"
    reference_image_path = os.path.join(vesper_root, "blender", "house_layout_reference.png")
    has_reference = os.path.exists(reference_image_path)
    
    print(f"🖼️ BGE: Reference image available: {has_reference}")
    if has_reference:
        print(f"📋 BGE: Using detailed reference + runtime screenshot for enhanced analysis")
    
    # Add imports for enhanced vision handling
    scene = bge.logic.getCurrentScene()
    actor = scene.objects.get("Actor")
    current_pos = f"[{actor.worldPosition.x:.1f}, {actor.worldPosition.y:.1f}]" if actor else "[unknown]"
    
    # Track position history to detect looping and drift
    if not hasattr(bge.logic, 'position_history'):
        bge.logic.position_history = []
    if not hasattr(bge.logic, 'analysis_count'):
        bge.logic.analysis_count = 0
    
    bge.logic.analysis_count += 1
    
    if actor:
        pos = (round(actor.worldPosition.x, 1), round(actor.worldPosition.y, 1))
        bge.logic.position_history.append(pos)
        # Keep only last 8 positions for loop detection
        if len(bge.logic.position_history) > 8:
            bge.logic.position_history.pop(0)
            
        # Detect looping behavior
        if len(bge.logic.position_history) >= 6:
            recent_positions = bge.logic.position_history[-6:]
            unique_positions = len(set(recent_positions))
            if unique_positions <= 3:
                print(f"🔄 BGE: LOOP DETECTED - Only {unique_positions} unique positions in last 6 moves")
                print(f"📍 BGE: Recent path: {recent_positions}")
            
        # Check if actor is drifting toward extreme coordinates
        if abs(actor.worldPosition.x) > 10 or abs(actor.worldPosition.y) > 10:
            print(f"⚠️ BGE: POSITION ALERT - Actor at extreme coordinates: {current_pos}")

    # Show which image we're analyzing
    image_filename = os.path.basename(screenshot_path)
    print(f"🔍 BGE: Analyzing image: {image_filename} - Actor at {current_pos}")

    # Add context about analysis frequency for VLM
    analysis_context = f"ANALYSIS #{bge.logic.analysis_count}"
    if bge.logic.analysis_count > 10:
        analysis_context += " - MANY ATTEMPTS! Focus on task completion."

    # Create enhanced system prompt based on available images
    if has_reference:
        system_prompt = """You are VESPER navigation AI with access to TWO images:
1. REFERENCE IMAGE: Detailed house layout showing all rooms and furniture clearly
2. RUNTIME IMAGE: Current bird's eye view with pink dot showing actor position

ANALYSIS STRATEGY:
- Use REFERENCE IMAGE to understand overall house layout and identify furniture
- Use RUNTIME IMAGE to locate the pink dot (actor) and determine current room
- Cross-reference between images to make accurate room identification

DUAL-IMAGE ROOM IDENTIFICATION:
REFERENCE IMAGE shows you:
- Complete house layout with all rooms
- Clear furniture details and placement
- Room boundaries and connections
- Kitchen appliances, bedroom furniture, living room setup

RUNTIME IMAGE shows you:
- Pink dot (actor) current position
- Real-time room view (may be lower quality)
- Actual navigation context

CRITICAL PROCESS:
1. Study REFERENCE IMAGE to understand house layout
2. Find pink dot in RUNTIME IMAGE
3. Match pink dot location to room in REFERENCE IMAGE
4. Identify specific furniture near pink dot using both images
5. Navigate based on comprehensive understanding"""
    else:
        system_prompt = """You are VESPER navigation AI. Analyze this bird's eye view screenshot to identify the current room and navigate efficiently."""

    system_prompt += """

CRITICAL ROOM IDENTIFICATION RULES:
BEDROOM = Look for: bed (rectangular furniture), dresser, nightstand, wardrobe, pillows
KITCHEN = Look for: stove/oven, refrigerator (large appliance), sink, countertops, cabinets
LIVING_ROOM = Look for: sofa/couch, coffee table, TV, chairs, entertainment center
OFFICE = Look for: desk, computer, office chair, bookshelf, work area
BATHROOM = Look for: toilet, sink, bathtub, shower, mirror
GARAGE = Look for: car, garage door, tools, workbench
UNKNOWN = If furniture is unclear or you cannot identify room type

FURNITURE RECOGNITION GUIDE:
- BED: Large rectangular furniture, usually with pillows/bedding
- SOFA: Long seating furniture, often L-shaped or rectangular
- STOVE: Cooking appliance with burners/cooking surface
- REFRIGERATOR: Large box-shaped appliance (usually white/metallic)
- TABLE: Flat surface furniture (coffee table = small, dining table = large)
- DRESSER: Tall furniture with drawers (bedroom storage)

The pink dot shows the actor's current position. Identify the room by analyzing furniture NEAR the pink dot."""

    # Add enhanced position context with spatial awareness
    position_context = ""
    if hasattr(bge.logic, 'position_history') and len(bge.logic.position_history) > 1:
        recent_positions = bge.logic.position_history[-3:]  
        position_context = f"\nRECENT POSITIONS: {recent_positions}"
        

        x, y = actor.worldPosition.x, actor.worldPosition.y
        spatial_hints = ""
        
        if x < -4.0:
            spatial_hints += " (Near LEFT edge of house - kitchen/bedroom area)"
        elif x > 0:
            spatial_hints += " (Near RIGHT edge of house - living room area)"
        else:
            spatial_hints += " (Center area of house)"
            
        if y > 4.0:
            spatial_hints += " (UPPER level - bedroom area)"
        elif y > 1.0:
            spatial_hints += " (Middle level - kitchen area)"  
        else:
            spatial_hints += " (Lower level - living room area)"
            
        position_context += spatial_hints
        
 
        if abs(x) > 5.0 or abs(y) > 5.0:
            position_context += " ⚠️ APPROACHING HOUSE BOUNDARIES!"


    if "bedroom" in current_task.lower():
        target_features = "BED (rectangular furniture), DRESSER/WARDROBE (tall furniture), PILLOWS, or bedroom-specific items"
        completion_criteria = "You must see a BED or bedroom furniture near the pink dot"
    elif "kitchen" in current_task.lower():
        target_features = "STOVE/OVEN (cooking appliances), REFRIGERATOR (large box), SINK, COUNTERTOPS, or kitchen cabinets"
        completion_criteria = "You must see kitchen appliances (stove, oven, fridge) or countertops near the pink dot"
    elif "living room" in current_task.lower() or "living" in current_task.lower():
        target_features = "SOFA/COUCH (seating furniture), COFFEE TABLE, TV, or living room furniture"
        completion_criteria = "You must see living room furniture near the pink dot"
    elif "office" in current_task.lower():
        target_features = "DESK (work surface), COMPUTER, OFFICE CHAIR, BOOKSHELF, or office equipment"
        completion_criteria = "You must see a DESK or office furniture near the pink dot"
    elif "bathroom" in current_task.lower():
        target_features = "TOILET (white porcelain), BATHTUB, SINK, SHOWER, or bathroom fixtures"
        completion_criteria = "You must see bathroom fixtures (toilet, bathtub, sink) near the pink dot"
    elif "garage" in current_task.lower():
        target_features = "CAR (vehicle), GARAGE DOOR, TOOLS, WORKBENCH, or garage equipment"
        completion_criteria = "You must see a CAR or garage equipment near the pink dot"
    else:
        target_features = "Any furniture or room-specific items"
        completion_criteria = "You must identify the correct room type and see appropriate furniture near the pink dot"

    # Create enhanced user prompt with image context
    image_context = ""
    if has_reference:
        image_context = f"""
DUAL-IMAGE ANALYSIS AVAILABLE:
- REFERENCE IMAGE: Detailed house layout (use for furniture identification)
- RUNTIME IMAGE: Current view with pink dot (use for position)

ENHANCED ANALYSIS PROCESS:
1. Study REFERENCE IMAGE to understand complete house layout
2. Identify all furniture and room boundaries in REFERENCE IMAGE
3. Locate pink dot in RUNTIME IMAGE
4. Cross-reference position with REFERENCE IMAGE layout
5. Use both images together for accurate room and furniture identification
"""
    else:
        image_context = "\nSINGLE IMAGE ANALYSIS: Using runtime screenshot only\n"

    user_prompt = f'''TASK: {current_task}
ANALYSIS #{bge.logic.analysis_count} | POSITION: {current_pos}{position_context}
{image_context}
STEP-BY-STEP VISUAL ANALYSIS:

1️. LOCATE PINK DOT: Find the pink/red dot showing actor position
   {f"(Use RUNTIME IMAGE to find pink dot, REFERENCE IMAGE for context)" if has_reference else ""}

2️. FURNITURE SCAN: Look at furniture immediately around the pink dot
   - What furniture is within 2-3 units of the pink dot?
   {f"- Cross-reference furniture details from REFERENCE IMAGE" if has_reference else ""}
   - Is it a BED (bedroom), SOFA (living room), STOVE (kitchen), or unclear?
   - CRITICAL: If image is blurry/unclear, describe what you actually see instead of using template text!

3️. ROOM IDENTIFICATION: Based on furniture near pink dot:
   🛏️ If you see BED/dresser/nightstand → BEDROOM
   🍳 If you see STOVE/refrigerator/sink/counters → KITCHEN  
   🛋️ If you see SOFA/couch/coffee table/TV → LIVING_ROOM
   🏢 If you see DESK/computer/office chair/bookshelf → OFFICE
   🚿 If you see TOILET/bathtub/sink/shower → BATHROOM
   🚗 If you see CAR/garage door/tools/workbench → GARAGE
   ❓ If furniture is unclear/blurry → UNKNOWN

4️. TASK CHECK: Does current room match task requirement?
   CURRENT TASK: "{current_task}"
   
   COMPREHENSIVE TASK-ROOM MATCHING:
   - Kitchen tasks ("cook", "kitchen") → MUST be in KITCHEN (see stove/refrigerator/sink)
   - Living room tasks ("relax", "living") → MUST be in LIVING_ROOM (see sofa/TV/coffee table)
   - Bathroom tasks ("prepare", "bathroom", "wash") → MUST be in BATHROOM (see toilet/bathtub/sink)
   - Bedroom tasks ("sleep", "bedroom", "rest") → MUST be in BEDROOM (see bed/dresser/nightstand)
   - Office tasks ("work", "office", "study") → MUST be in OFFICE (see desk/computer/chair)
   - Garage tasks ("car", "garage", "park") → MUST be in GARAGE (see car/garage door/tools)
   
5️. NAVIGATION DECISION:
   TASK COMPLETE ONLY IF: Current room type EXACTLY matches task requirement
      - Kitchen task + KITCHEN room + kitchen furniture = task_complete: true
      - Bathroom task + BATHROOM room + bathroom fixtures = task_complete: true
      - Living room task + LIVING_ROOM room + living room furniture = task_complete: true
      - Bedroom task + BEDROOM room + bedroom furniture = task_complete: true
      - Office task + OFFICE room + office furniture = task_complete: true
      - Garage task + GARAGE room + garage equipment = task_complete: true
   
   TASK INCOMPLETE IF: Wrong room or unclear room
      - Kitchen task but in BEDROOM/BATHROOM/LIVING_ROOM/OFFICE/GARAGE = task_complete: false
      - Bathroom task but in KITCHEN/BEDROOM/LIVING_ROOM/OFFICE/GARAGE = task_complete: false
      - Any task but UNKNOWN room = task_complete: false, try movement for clarity

   CRITICAL: NEVER set task_complete: true unless room type perfectly matches task!

FURNITURE EXAMPLES TO RECOGNIZE:
BED: Large rectangular shape, often with pillows/headboard
SOFA: L-shaped or long rectangular seating, multiple cushions
STOVE: Square/rectangular with cooking surfaces/burners
TV: Flat rectangular screen, often on stand or wall
TABLE: Flat surface (coffee table = small round/square, dining = large)
DESK: Flat work surface, often with computer or papers
TOILET: White porcelain fixture, bowl shape
BATHTUB: Large white rectangular basin
CAR: Large vehicle shape in enclosed space
TOOLS: Hanging implements, workbench, garage equipment

CRITICAL: Focus on furniture IMMEDIATELY AROUND the pink dot to determine room type!

NAVIGATION RULES:
- If current room matches task: Use ["STAY"] and set task_complete: true
- If in wrong room but know which direction to go: Use ONE direction like ["LEFT"] or ["UP"]
- From LIVING_ROOM to KITCHEN: Try ["LEFT"] or ["UP"] (kitchen typically connected to living area)
- From any room to BATHROOM: Try ["UP"] or ["RIGHT"] (bathrooms often upstairs/corners)
- From any room to BEDROOM: Try ["UP"] or ["RIGHT"] (bedrooms often upstairs/sides)
- If completely lost or image unclear: Use ["STAY"] and request better view
- NEVER use multiple directions in sequence like ["UP", "DOWN", "LEFT", "RIGHT"]
- ALWAYS try ONE direction at a time for exploration

ANTI-OSCILLATION RULES:
- NEVER use template text like "list specific furniture you see near pink dot"
- ALWAYS describe what you actually observe, even if unclear
- If image is blurry, try ONE direction only to get better view
- If stuck for 3+ cycles, try a DIFFERENT direction
- NEVER suggest staying when not in correct room - ALWAYS try movement

JSON Response (REQUIRED FORMAT):
{{
  "current_room": "BEDROOM|KITCHEN|LIVING_ROOM|OFFICE|BATHROOM|GARAGE|UNKNOWN",
  "furniture_visible": ["describe actual furniture you see, not template text"],
  "task_complete": true/false,
  "movement_sequence": ["SINGLE_DIRECTION"] or ["STAY"],
  "reasoning": "FURNITURE SEEN: [actual items observed]. ROOM: [determined room]. TASK: [complete/need to move to X]"
}}

Movement options: "UP", "DOWN", "LEFT", "RIGHT", "STAY" ONLY (use ONE direction when unclear!)'''

    # ENHANCED: Use IMAGES ONLY - no text fallback
    if has_reference:
        print("🔍 BGE: IMAGES-ONLY Analysis - Using runtime screenshot with reference context...")
        
        # Skip problematic reference image analysis - use runtime image only with enhanced context
        enhanced_prompt = f"""IMPORTANT: You have access to a detailed house layout that shows:
- LIVING ROOM: Contains sofa, coffee table, TV (typically in center-right area)  
- KITCHEN: Contains stove, refrigerator, sink, counters (typically in left area, connected to living room)
- BEDROOM: Contains bed, dresser, nightstand (typically in upper areas)
- BATHROOM: Contains toilet, bathtub, sink (typically smaller rooms, often upstairs)
- OFFICE: Contains desk, computer, office chair (if present)
- GARAGE: Contains car, tools, garage door (if present)

NAVIGATION HINTS FOR TASK "{current_task}":
🏠 House Layout: Kitchen is typically LEFT or UP from living room center
🎯 Your Goal: Navigate FROM current room TO target room for task completion
📍 Current Analysis: Look at furniture around pink dot to identify current room
🧭 Movement Strategy: If wrong room, try ONE direction toward target (LEFT/UP for kitchen from living room)

CURRENT TASK: {current_task}

NOW ANALYZE this runtime image with the pink dot:

{system_prompt}

{user_prompt}

CRITICAL: Use the runtime image to:
1. Locate the pink dot (actor position)  
2. Identify furniture around the pink dot
3. Match furniture to room type
4. Make navigation decision

IMAGES-ONLY ANALYSIS: Base your response entirely on what you see in this runtime image."""

        print("🔍 BGE: Analyzing runtime image with enhanced layout context...")
        response = vision_only_completion(enhanced_prompt, screenshot_path)
        
        print("✅ BGE: Images-only analysis completed successfully")
    else:
        # Standard single-image analysis
        print("🔍 BGE: Standard images-only analysis...")
        response = vision_only_completion(
            f"{system_prompt}\n\n{user_prompt}",
            screenshot_path
        )
        
        print("✅ BGE: Standard vision analysis completed")

    print(f"🔍 BGE: VLM Response → {response[:300]}...")  # Show first 300 chars

    # Parse response with improved error handling and task validation
    return parse_vlm_response(response, current_task)

# =============================
# Movement
# =============================
def move_actor(actor, direction, step_size=0.3):
    """Move actor in BGE coordinate system with safety boundaries"""
    if direction == "STAY":
        print("🛑 BGE: Actor staying - task complete!")
        return True

    current_pos = actor.worldPosition.copy()
    print(f"🔍 BGE: Before move - Actor at [{current_pos.x:.2f}, {current_pos.y:.2f}]")
    
    # Calculate proposed new position
    proposed_pos = current_pos.copy()
    if direction == "UP":
        proposed_pos.y += step_size
    elif direction == "DOWN":
        proposed_pos.y -= step_size
    elif direction == "LEFT":
        proposed_pos.x -= step_size
    elif direction == "RIGHT":
        proposed_pos.x += step_size
    
    # CRITICAL: House boundary enforcement to prevent actor from leaving
    # Based on log analysis, safe house boundaries appear to be approximately:
    HOUSE_BOUNDS = {
        'x_min': -6.0,   # Left boundary
        'x_max': 2.0,    # Right boundary  
        'y_min': -1.0,   # Bottom boundary
        'y_max': 6.0     # Top boundary
    }
    
    # Check if proposed move would leave house boundaries
    if (proposed_pos.x < HOUSE_BOUNDS['x_min'] or proposed_pos.x > HOUSE_BOUNDS['x_max'] or
        proposed_pos.y < HOUSE_BOUNDS['y_min'] or proposed_pos.y > HOUSE_BOUNDS['y_max']):
        
        print(f"🚨 BGE: BOUNDARY VIOLATION PREVENTED!")
        print(f"   Proposed position: [{proposed_pos.x:.2f}, {proposed_pos.y:.2f}]")
        print(f"   House bounds: X({HOUSE_BOUNDS['x_min']} to {HOUSE_BOUNDS['x_max']}), Y({HOUSE_BOUNDS['y_min']} to {HOUSE_BOUNDS['y_max']})")
        print(f"   🛑 Movement {direction} BLOCKED - staying in current position")
        return False  # Movement blocked
    
    # Apply the safe movement
    actor.worldPosition = proposed_pos
    new_pos = actor.worldPosition
    print(f"🎮 Moved {direction} → [{new_pos.x:.2f}, {new_pos.y:.2f}]")
    
    # Additional safety check after movement
    if (abs(new_pos.x) > 10 or abs(new_pos.y) > 10):
        print(f"🚨 BGE: EMERGENCY: Actor at extreme coordinates!")
        print(f"   Resetting to safe position...")
        # Reset to safe center position
        actor.worldPosition.x = -2.0
        actor.worldPosition.y = -0.5
        print(f"   🔧 Reset to safe position: [{actor.worldPosition.x:.2f}, {actor.worldPosition.y:.2f}]")
        
    return True


def main():
    """Main BGE navigation function with sequence-based movement (non-blocking screenshots, manual camera settings preserved)"""
    controller = bge.logic.getCurrentController()
    scene = bge.logic.getCurrentScene()

    # Find actor
    actor = scene.objects.get("Actor")
    if not actor:
        print("❌ BGE: No 'Actor' object found!")
        return

    # Init state once
    if not hasattr(bge.logic, "vesper_nav_init"):
        bge.logic.vesper_nav_init = True
        bge.logic.vesper_current_task_index = 0
        
        # Load tasks from vesper_tasks.txt (generated by addon)
        vesper_tasks = load_vesper_tasks()
        bge.logic.vesper_tasks = vesper_tasks if vesper_tasks else ["Go to bedroom", "Cook in kitchen", "Rest in bedroom"]
        
        bge.logic.vesper_movement_queue = []  # sequence of moves
        bge.logic.vesper_sequence_step = 0
        bge.logic.last_screenshot_path = None

        print("🧠 BGE: VESPER Navigation initialized!")
        print(f"📋 BGE: Tasks: {bge.logic.vesper_tasks}")
        print(f"📍 BGE: LLM Available: {LLM_AVAILABLE}")
        print("🔧 BGE: Camera calibration DISABLED - your manual settings preserved!")
        
        # ENHANCED: Display screenshot quality recommendations
        print("\n📸 BGE: SCREENSHOT QUALITY RECOMMENDATIONS:")
        print("   💡 For best VLM analysis, ensure:")
        print("   🎯 BirdEyeCamera positioned high (Z > 8) for complete room view")
        print("   📐 Camera lens 35mm+ for wide coverage")
        print("   🖥️ BGE window size 1024x768+ for better resolution")
        print("   🎨 Good lighting in all rooms")
        print("   📏 Actor (pink dot) clearly visible against floor")

        # Kick off initial screenshot (non-blocking)
        print("\n📸 BGE: Requesting initial high-quality screenshot...")
        request_bird_eye_screenshot()
        return  # yield this tick so a frame can render

    # If a screenshot is pending, poll it
    shot_status = poll_screenshot_ready()
    if shot_status is None:
        # Not ready yet; let the engine render another frame
        pass
    elif shot_status == "TIMEOUT":
        # Re-request next frame
        request_bird_eye_screenshot()
        return
    else:
        # Ready path
        bge.logic.last_screenshot_path = shot_status

    # Stop if all tasks done
    if bge.logic.vesper_current_task_index >= len(bge.logic.vesper_tasks):
        print("🎉 BGE: ALL TASKS COMPLETED!")
        return

    current_task = bge.logic.vesper_tasks[bge.logic.vesper_current_task_index]

    # If we need a new movement plan
    if not bge.logic.vesper_movement_queue:
        # Ensure we have a screenshot (request one if we don't)
        if not bge.logic._vesper_shot["pending"] and not bge.logic.last_screenshot_path:
            print(f"\n📍 Planning: {current_task}")
            print("📸 BGE: Requesting fresh screenshot for analysis...")
            request_bird_eye_screenshot()
            return  # allow frame to render

        # If a recent screenshot is ready, analyze it
        if bge.logic.last_screenshot_path:
            try:
                sequence_result = get_navigation_sequence_with_vlm(bge.logic.last_screenshot_path, current_task)
                if "movement_sequence" in sequence_result:
                    bge.logic.vesper_movement_queue = sequence_result["movement_sequence"].copy()
                    bge.logic.vesper_sequence_step = getattr(bge.logic, 'vesper_sequence_step', 0)
                    
                    # Store VLM analysis results for validation
                    bge.logic.vlm_analysis = {
                        "task_complete": sequence_result.get("task_complete", False),
                        "current_room": sequence_result.get("current_room", "UNKNOWN"),
                        "furniture_visible": sequence_result.get("furniture_visible", "None"),
                        "reasoning": sequence_result.get("reasoning", "")
                    }
                    
                    print(f"🎯 BGE: Loaded sequence: {bge.logic.vesper_movement_queue}")
                    print(f"🏠 BGE: Room Analysis - Current: {bge.logic.vlm_analysis['current_room']}")
                    print(f"🪑 BGE: Furniture: {bge.logic.vlm_analysis['furniture_visible']}")
                    print(f"💭 BGE: {sequence_result.get('reasoning', 'No reasoning provided')}")
                    
                    # Check if VLM says task is complete
                    if bge.logic.vlm_analysis["task_complete"]:
                        print(f"🎯 BGE: VLM confirms task complete - actor in correct room!")
                else:
                    raise Exception("❌ VLM did not return movement_sequence - critical error")
            finally:
                # Consume this screenshot; next cycle will take a new one
                bge.logic.last_screenshot_path = None

    # Execute next step if we have a plan
    if bge.logic.vesper_movement_queue:
        next_move = bge.logic.vesper_movement_queue.pop(0)
        bge.logic.vesper_sequence_step += 1

        print(f"🎮 BGE: Step {bge.logic.vesper_sequence_step}: {next_move}")
        print(f"📍 Queue: {bge.logic.vesper_movement_queue}")

        old_position = [actor.worldPosition.x, actor.worldPosition.y]
        move_success = move_actor(actor, next_move)
        new_position = [actor.worldPosition.x, actor.worldPosition.y]

        # Position drift detection - check if actor is moving to extreme coordinates
        if abs(new_position[0]) > 15 or abs(new_position[1]) > 15:
            print(f"🚨 BGE: EXTREME POSITION DETECTED! Actor at [{new_position[0]:.1f}, {new_position[1]:.1f}]")
            print("🔄 BGE: Position appears outside house - requesting immediate visual re-analysis")
            bge.logic.vesper_movement_queue = []  # clear current plan
            if not bge.logic._vesper_shot["pending"]:
                request_bird_eye_screenshot()
            return

        # Detect if stuck (position didn't change)
        moved_distance = ((new_position[0] - old_position[0])**2 + (new_position[1] - old_position[1])**2)**0.5
        if moved_distance < 0.1 and next_move != "STAY":
            print("⚠️ BGE: Actor appears stuck or movement blocked by safety boundaries")
            bge.logic.vesper_movement_queue = []  # trigger replanning
            # Request new screenshot immediately
            if not bge.logic._vesper_shot["pending"]:
                request_bird_eye_screenshot()
            return

        # If the short sequence is finished, request a new screenshot for the next cycle
        if not bge.logic.vesper_movement_queue:
            print("📸 BGE: Short sequence completed - requesting NEW screenshot for re-analysis")
            
            # Enhanced task completion validation
            if next_move == "STAY":
                # Validate task completion based on VLM room analysis
                vlm_analysis = getattr(bge.logic, 'vlm_analysis', {})
                task_complete_confirmed = vlm_analysis.get("task_complete", False)
                current_room = vlm_analysis.get("current_room", "UNKNOWN")
                furniture_visible = vlm_analysis.get("furniture_visible", "None")
                
                if task_complete_confirmed:
                    print(f"✅ BGE: Task '{current_task}' VALIDATED - Actor confirmed in correct room!")
                    print(f"🏠 BGE: Final location: {current_room}")
                    print(f"🪑 BGE: Furniture confirmation: {furniture_visible}")
                    bge.logic.vesper_current_task_index += 1
                    bge.logic.vesper_sequence_step = 0
                    
                    # Clear VLM analysis for next task
                    bge.logic.vlm_analysis = {}
                else:
                    print(f"⚠️ BGE: STAY command but task NOT validated!")
                    print(f"🏠 BGE: Current room: {current_room} (target needed for '{current_task}')")
                    print(f"🔄 BGE: Continuing navigation - need to reach correct room")
                    # Don't advance task index - continue navigation
            else:
                print(f"🔄 BGE: Continuing task '{current_task}' with new analysis cycle")

            # Request the next screenshot right away
            if not bge.logic._vesper_shot["pending"]:
                request_bird_eye_screenshot()
            return

if __name__ == "__main__":
    main()
